# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build WebApp

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 21.x
        uses: actions/setup-node@v3
        with:
          node-version: 21.x
          cache: "npm"
          working-directory: ./Rewards.Todoist.WebApp
      - run: npm ci
        working-directory: ./Rewards.Todoist.WebApp
      - run: npm run build --if-present
        working-directory: ./Rewards.Todoist.WebApp
      - run: npm test
        working-directory: ./Rewards.Todoist.WebApp
