name: Build WebApp

on:
  push:
    branches: ["master"]
    paths: [frontend, .github/workflows/node.js.yml]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 21.x
        uses: actions/setup-node@v3
        with:
          node-version: 21.x
          cache: "npm"
          cache-dependency-path: ${{ github.workspace }}/frontend/package-lock.json
      - run: npm ci
        working-directory: ./frontend
      - run: npm run build --if-present
        working-directory: ./frontend
